# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-abaco-agri-stub:
    build:
      target: development
    image: ffc-tcg-abaco-agri-stub-development
    container_name: ffc-tcg-abaco-agri-stub-development
    ports:
      - "3052:3052"
      - "9252:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-tcg-abaco-agri-stub-redis:
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --dir /data --save 5 1

volumes:
  redis_data:
