services:
  ffc-tcg-abaco-agri-stub:
    build:
      context: .
      target: production
    image: ffc-tcg-abaco-agri-stub
    container_name: ffc-tcg-abaco-agri-stub
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-abaco-agri-stub-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
