environment: production
environmentCode:
name: ffc-tcg-abaco-agri-stub
namespace: ffc-tcg
workstream: ffc-tcg
image: ffc-tcg-abaco-agri-stub

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-abaco-agri-stub-config-map

containerSecret:
  name: ffc-tcg-abaco-agri-stub-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3052

livenessProbe:
  path: /healthz
  port: 3052
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3052
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
