{{- if .Values.aadPodIdentity }}
{{- include "ffc-helm-library.azure-identity" (list . "ffc-tcg-abaco-agri-stub.azure-identity") -}}
{{- end }}
{{- define "ffc-tcg-abaco-agri-stub.azure-identity" -}}
{{- end -}}
