{{- include "ffc-helm-library.container-config-map" (list . "ffc-tcg-abaco-agri-stub.config-map") -}}
{{- define "ffc-tcg-abaco-agri-stub.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
{{- end -}}
